name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    name: "Cypress Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run server
        run: npm run dev
      - name: Run Cypress tests
        run: |
          npm install
          npm run build
          cd tests
          npm install
          npm run dev &
          npm run test
          lsof -t -i tcp:3000 | xargs kill
